In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors
## Creating Tensors
PyTorch tensors are created using <a href="https://pytorch.org/docs/stable/tensors.html">`torch.Tensor()`</a>



In [2]:
# scalar
scalar = torch.tensor(7)
print(scalar)
vector = torch.tensor([1, 2, 3])
print(vector)
# when making a matrix each subarray has to be the same size, you cannot have [[1], [1, 2], [1]]
matrix = torch.tensor([[1,2], [3, 4]])
print(matrix)
# anything with more dimensions that a matrix is called a tensor
tensor = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(tensor)

tensor(7)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


To get the value as an int or array and not a tensor, you can use <a href="https://pytorch.org/docs/stable/generated/torch.Tensor.item.html#torch-tensor-item">`item()`</a> for tensors with a single value or <a href="https://pytorch.org/docs/stable/generated/torch.Tensor.tolist.html#torch.Tensor.tolist">`tolist()`</a> for more complex tensors.

In [3]:
print(scalar.item())
print(vector.tolist())
print(matrix.tolist())
print(tensor.tolist())

7
[1, 2, 3]
[[1, 2], [3, 4]]
[[[1, 2, 3], [1, 2, 3], [1, 2, 3]]]


Use tensor.ndim to check the dimensions of the tensor.

In [4]:
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)

0
1
2
3


To see how many elements it contains use shape

In [5]:
print(scalar.shape)
print(vector.shape)
# the result for the following will be [2, 2] which means 2 arrays with 2 elements each
print(matrix.shape)
# the result for the following will be [1, 3, 3] which means one array with 3 sub arrays, with 3 elements each.
print(tensor.shape)

torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([1, 3, 3])


## Random tensors
### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represet the data.
#### How a neural networks works
`Start with random numbers => Look at Data => Update random numbers => Look at data => Update random numbers...`
#### How to create a random tensor
You call <a href="https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand">`torch.rand()`</a> and pass in the size/shape of the tensor as params, in the following example code we will create a tensor with the same size as the one we had earlier.

In [6]:

randomTensor = torch.rand(1, 3, 3)
print(randomTensor)

tensor([[[0.8146, 0.2097, 0.0613],
         [0.3419, 0.3797, 0.1965],
         [0.1912, 0.4321, 0.8923]]])


### Data to tensor
Almost anything can be represented as data. For example images are usually 3 dimensional tensors, they have a dimension for height, one for witdth, and one for the color channels composed of red, green and blue. So let's say we want to create an image of size 224x224 here is what you would do.

In [7]:
randomImageTensor = torch.rand(224, 224, 3)
randomImageTensor

tensor([[[0.6648, 0.6860, 0.0954],
         [0.7584, 0.0569, 0.7815],
         [0.2725, 0.7097, 0.6243],
         ...,
         [0.9027, 0.1223, 0.6513],
         [0.7032, 0.5389, 0.1296],
         [0.9399, 0.4005, 0.8321]],

        [[0.6462, 0.5100, 0.8014],
         [0.7859, 0.5020, 0.1791],
         [0.5177, 0.9904, 0.8914],
         ...,
         [0.6367, 0.1961, 0.1284],
         [0.9896, 0.8159, 0.5497],
         [0.5358, 0.2593, 0.5331]],

        [[0.5832, 0.9838, 0.1349],
         [0.9396, 0.8903, 0.7636],
         [0.7055, 0.9801, 0.2040],
         ...,
         [0.1778, 0.5353, 0.6465],
         [0.4946, 0.2739, 0.6257],
         [0.5057, 0.2838, 0.6095]],

        ...,

        [[0.4726, 0.3106, 0.3105],
         [0.0317, 0.4078, 0.1970],
         [0.9271, 0.9292, 0.6788],
         ...,
         [0.4692, 0.3973, 0.1905],
         [0.6793, 0.8476, 0.5647],
         [0.8956, 0.6769, 0.7057]],

        [[0.5211, 0.7964, 0.6447],
         [0.9922, 0.0738, 0.7460],
         [0.

### Zeros and ones

In [8]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

To check the data type of your tensor use `Tensor.dtype`, by default that is torch.float32

In [10]:
ones.dtype

torch.float32

You can also turn any tensor into zeros

In [11]:
torch.zeros_like(input=tensor), torch.zeros_like(input=randomImageTensor)

(tensor([[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.

### Creating a range of tensors

In [12]:
oneToTen = torch.arange(start=1, end=11, step=1)# does not include 11, by default the step is 1
twoTimesTable = torch.arange(start=2, end=21, step=2)
oneToTen, twoTimesTable

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))

## Tensor Params


Tensors with different shapes, or/and device cannot be used in the same operation, for example multiplications. Sometimes you might get errors if they have different data types too.

In [13]:
float32Tensor = torch.tensor([[1.0], [2.0], [3.0]],
                             dtype=None,# data type, float32 by default
                             device=None,# what device it's on
                             requires_grad=False)# if it requires a gradient to be calculated
try:
  matrix * float32Tensor
except RuntimeError as e:
  print(float32Tensor.shape)
  print(matrix.shape)
  print(e)

torch.Size([3, 1])
torch.Size([2, 2])
The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0


In [14]:
randomIntTensor = torch.randint(low=0, high=2, size=[1, 2, 3])
randomFloatTensor = torch.rand(2, 3, 3, dtype=torch.float16) # this function cannot be used for ints
randomIntTensor, randomFloatTensor

(tensor([[[0, 0, 1],
          [0, 1, 1]]]),
 tensor([[[0.0698, 0.7837, 0.0688],
          [0.7710, 0.4668, 0.3008],
          [0.8281, 0.8896, 0.4521]],
 
         [[0.8462, 0.5195, 0.3115],
          [0.6089, 0.4424, 0.8462],
          [0.2114, 0.5679, 0.3247]]], dtype=torch.float16))

## Manipulating Tensors
You can only add, subtract, multiply and divide, two tensors with the same shape, or if one of the tensors has no dimensions (it's just one number).

However, there is an exception, this is when you multiply tensors, in this case they can be different shapes, but there are limitations; look into matrix multiplications.
### Addittion

In [15]:
tensor = torch.tensor([1, 2, 3])
second_tensor = torch.tensor([4, 5, 6])
tensor + 10, torch.add(tensor, 10), tensor + second_tensor, torch.add(tensor, second_tensor)

(tensor([11, 12, 13]),
 tensor([11, 12, 13]),
 tensor([5, 7, 9]),
 tensor([5, 7, 9]))

### Subtraction

In [16]:
tensor - 10, torch.sub(tensor, 10), tensor - second_tensor, torch.sub(tensor, second_tensor)

(tensor([-9, -8, -7]),
 tensor([-9, -8, -7]),
 tensor([-3, -3, -3]),
 tensor([-3, -3, -3]))

### Division

In [17]:
tensor / 10, torch.div(tensor, 10), tensor / second_tensor, torch.div(tensor, second_tensor)

(tensor([0.1000, 0.2000, 0.3000]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([0.2500, 0.4000, 0.5000]),
 tensor([0.2500, 0.4000, 0.5000]))

### Element wise multiplication

In [18]:
tensor * 10, torch.mul(tensor, 10), tensor * second_tensor, torch.mul(tensor, second_tensor)

(tensor([10, 20, 30]),
 tensor([10, 20, 30]),
 tensor([ 4, 10, 18]),
 tensor([ 4, 10, 18]))

### Matrix multiplication
When multiplying matricies it is important to know that:
1. The **inner dimensions** must match:
  - `(3, 2) @ (3, 2) won't work`
  - `(2, 3) @ (3, 2) will work`
  - `(3, 2) @ (2, 3) will work`
2. The resulting matrix has the shape of the **outer dimensions**:
  - `(2, 3) @ (3, 2) => (2, 2)`
  - `(3, 2) @ (2, 3) => (3, 3)`
  - `(3, 2) @ (2, 2) => (3, 2)`

In [19]:
third_tensor = torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(tensor.shape)
print(second_tensor.shape)
print(third_tensor.shape)
print(tensor @ third_tensor)
print(tensor @ second_tensor)
print(torch.matmul(tensor, third_tensor))
print(torch.matmul(tensor, second_tensor))
print(torch.matmul(tensor, third_tensor).shape)
print(torch.matmul(tensor, second_tensor).shape)

torch.Size([3])
torch.Size([3])
torch.Size([3, 3])
tensor([ 6, 12, 18])
tensor(32)
tensor([ 6, 12, 18])
tensor(32)
torch.Size([3])
torch.Size([])


In [20]:
randMatMul = torch.mm(torch.rand(2, 10), torch.rand(10, 7)) # mm is an alias for matmul
randMatMul.shape

torch.Size([2, 7])

## Common error in deep learning
When multiplying matricies, you might have two matricies with a shape of 3x2 3x2, you cannot multiply these two, but there is a work around, and this is to transpose one of them to make it a 2x3 matrix.

In [21]:
tensor_A = torch.rand(3, 2)
tensor_B = torch.rand(3, 2)
try:
  torch.mm(tensor_A, tensor_B)
except RuntimeError as e:
  print(e)
print("tensor_B:")
print(tensor_B)
print(tensor_B.shape)
print("tensor_B.T (transposed):")
print(tensor_B.T)
print(tensor_B.T.shape)
print("mm result:")
print(torch.mm(tensor_A, tensor_B.T))
print(torch.mm(tensor_A, tensor_B.T).shape)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
tensor_B:
tensor([[0.5860, 0.5275],
        [0.3997, 0.4217],
        [0.3935, 0.9402]])
torch.Size([3, 2])
tensor_B.T (transposed):
tensor([[0.5860, 0.3997, 0.3935],
        [0.5275, 0.4217, 0.9402]])
torch.Size([2, 3])
mm result:
tensor([[0.4576, 0.3534, 0.6979],
        [0.2457, 0.1729, 0.2151],
        [0.3973, 0.2763, 0.3166]])
torch.Size([3, 3])


## Finding the min, max, mean, sum... of a Tensor (tensor aggregation)


In [22]:
x = torch.arange(1, 100, 10)
print(x)
print(torch.min(x))
print(x.min())
print(torch.max(x))
print(x.max())
print(torch.mean(x, dtype=torch.float16))
print(torch.mean(x.type(torch.float16)))
print(x.type(torch.float16).mean())
print(torch.sum(x))
print(x.sum())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1)
tensor(1)
tensor(91)
tensor(91)
tensor(46., dtype=torch.float16)
tensor(46., dtype=torch.float16)
tensor(46., dtype=torch.float16)
tensor(460)
tensor(460)


In [23]:
# You also can easily find the index of the min and max values
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, Stacking, Squeezing and unsqueezing

In [24]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [25]:
y = torch.rand(3, 2, 1, 4)
y, y.shape

(tensor([[[[0.5185, 0.3782, 0.6946, 0.9748]],
 
          [[0.2983, 0.0036, 0.1538, 0.3116]]],
 
 
         [[[0.1996, 0.0413, 0.6894, 0.0167]],
 
          [[0.4308, 0.2700, 0.4402, 0.8357]]],
 
 
         [[[0.9163, 0.5511, 0.3513, 0.3246]],
 
          [[0.1550, 0.6656, 0.3225, 0.3507]]]]),
 torch.Size([3, 2, 1, 4]))

### Reshaping
Reshapes an input tensor to a defined shape

In [26]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [27]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [28]:
y_reshaped = y.reshape(1, 2, 3, 4)
y_reshaped, y_reshaped.shape

(tensor([[[[0.5185, 0.3782, 0.6946, 0.9748],
           [0.2983, 0.0036, 0.1538, 0.3116],
           [0.1996, 0.0413, 0.6894, 0.0167]],
 
          [[0.4308, 0.2700, 0.4402, 0.8357],
           [0.9163, 0.5511, 0.3513, 0.3246],
           [0.1550, 0.6656, 0.3225, 0.3507]]]]),
 torch.Size([1, 2, 3, 4]))

### View
A view of a tensor is the same tensor (shares the same memory), so changing it will change the original

In [29]:
z = x.view(9, 1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [30]:
z[0][0] = 5
z, x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stack

In [31]:
x_stacked_v = torch.stack([x, x, x, x], dim=0)
x_stacked_h = torch.stack([x, x, x, x], dim=1)
x, x_stacked_v, x_stacked_h

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

### Squeeze
It removes all single dimensions

In [32]:
y_squeezed = torch.squeeze(y)
y, y.shape, y_squeezed, y_squeezed.shape

(tensor([[[[0.5185, 0.3782, 0.6946, 0.9748]],
 
          [[0.2983, 0.0036, 0.1538, 0.3116]]],
 
 
         [[[0.1996, 0.0413, 0.6894, 0.0167]],
 
          [[0.4308, 0.2700, 0.4402, 0.8357]]],
 
 
         [[[0.9163, 0.5511, 0.3513, 0.3246]],
 
          [[0.1550, 0.6656, 0.3225, 0.3507]]]]),
 torch.Size([3, 2, 1, 4]),
 tensor([[[0.5185, 0.3782, 0.6946, 0.9748],
          [0.2983, 0.0036, 0.1538, 0.3116]],
 
         [[0.1996, 0.0413, 0.6894, 0.0167],
          [0.4308, 0.2700, 0.4402, 0.8357]],
 
         [[0.9163, 0.5511, 0.3513, 0.3246],
          [0.1550, 0.6656, 0.3225, 0.3507]]]),
 torch.Size([3, 2, 4]))

### Unsqueezing
Adds one dimension, at the specified index

In [33]:
y_unsqueezed_0 = y_squeezed.unsqueeze(0)
y_unsqueezed_1 = y_squeezed.unsqueeze(1)
y_unsqueezed_2 = y_squeezed.unsqueeze(2)
y_unsqueezed_3 = y_squeezed.unsqueeze(3)
y_u = torch.unsqueeze(y, 0)
y_squeezed, y_squeezed.shape, y_unsqueezed_0, y_unsqueezed_0.shape, y_unsqueezed_1, y_unsqueezed_1.shape, y_unsqueezed_2, y_unsqueezed_2.shape, y_unsqueezed_3, y_unsqueezed_3.shape, y_u, y_u.shape

(tensor([[[0.5185, 0.3782, 0.6946, 0.9748],
          [0.2983, 0.0036, 0.1538, 0.3116]],
 
         [[0.1996, 0.0413, 0.6894, 0.0167],
          [0.4308, 0.2700, 0.4402, 0.8357]],
 
         [[0.9163, 0.5511, 0.3513, 0.3246],
          [0.1550, 0.6656, 0.3225, 0.3507]]]),
 torch.Size([3, 2, 4]),
 tensor([[[[0.5185, 0.3782, 0.6946, 0.9748],
           [0.2983, 0.0036, 0.1538, 0.3116]],
 
          [[0.1996, 0.0413, 0.6894, 0.0167],
           [0.4308, 0.2700, 0.4402, 0.8357]],
 
          [[0.9163, 0.5511, 0.3513, 0.3246],
           [0.1550, 0.6656, 0.3225, 0.3507]]]]),
 torch.Size([1, 3, 2, 4]),
 tensor([[[[0.5185, 0.3782, 0.6946, 0.9748],
           [0.2983, 0.0036, 0.1538, 0.3116]]],
 
 
         [[[0.1996, 0.0413, 0.6894, 0.0167],
           [0.4308, 0.2700, 0.4402, 0.8357]]],
 
 
         [[[0.9163, 0.5511, 0.3513, 0.3246],
           [0.1550, 0.6656, 0.3225, 0.3507]]]]),
 torch.Size([3, 1, 2, 4]),
 tensor([[[[0.5185, 0.3782, 0.6946, 0.9748]],
 
          [[0.2983, 0.0036, 0.1538,

### Premute
Rearranges the dimensions of a target tensor in a specified order.
It is important to note that torch.permute or tensor.permute, will return a view, which means it shares the same memory as the original tensor, modifying one of them will modify the other.

In [34]:
r_image = torch.rand(size=(1920, 1080, 3)) # rand image => size = [0 = height, 1 = width, 2 = colour_channels]; it is important to notice the index
r_image_permuted = torch.permute(r_image, (2, 0, 1)) # the shape has been changed, this works with indexes, so the size at index 2 was moved to be the first one etc...
r_image.shape, r_image_permuted.shape

(torch.Size([1920, 1080, 3]), torch.Size([3, 1920, 1080]))

## Indexing (selecting data from arrays)

In [35]:
import torch

x = torch.arange(1, 21).reshape(2, 2, 5)
x, x.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]]),
 torch.Size([2, 2, 5]))

In [36]:
x[0], x[0][0], x[0][1][2]

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([1, 2, 3, 4, 5]),
 tensor(8))

In [37]:
x[:, 0], x[:, 1], x[:, :, 1], x[:, 1, 1]# : means all

(tensor([[ 1,  2,  3,  4,  5],
         [11, 12, 13, 14, 15]]),
 tensor([[ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 20]]),
 tensor([[ 2,  7],
         [12, 17]]),
 tensor([ 7, 17]))

In [38]:
x[:, :, 2].reshape(4)

tensor([ 3,  8, 13, 18])

## Pytorch tensors and NumPy
NumPy is a popular scientific Python numerical computing library.
Pytorch has functionality to interact with it.

When converting, the two arrays will not share the same memory changing one will not affect the other.

In [39]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy the datetype will be float64 as that is the default for numpy, if you want it to be float32 (torch's default) then you have to manually convert it with type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

You can also convert from tensor to numpy

In [40]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers and make them better -> repeat`

To reducen the randomness in neaural networksand pytorch comes the concept of **random seed**.
What is does, is that it flavours the randomness.

In [41]:
import torch

RANDOM_SEED = 432
torch.manual_seed(RANDOM_SEED) # this only works for one block of code
A = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
B = torch.rand(3, 4)
A, B, A == B

(tensor([[0.3371, 0.3477, 0.3786, 0.6942],
         [0.0272, 0.1464, 0.7420, 0.8068],
         [0.0105, 0.6451, 0.4570, 0.8700]]),
 tensor([[0.3371, 0.3477, 0.3786, 0.6942],
         [0.0272, 0.1464, 0.7420, 0.8068],
         [0.0105, 0.6451, 0.4570, 0.8700]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

# Running tensors and pytorch objects on GPUs

### Getting a GPU
1. Use Google colab for a free GPU (options to upgrade) - Easiest.
2. Use your own GPU - Requires a bit of setup
3. Use cloud computing - GCP, AWS, Azure

For option 2, 3, look at the pytorch setup docs.

**It is important to note that numpy does not work on GPUs therefore you cannot convert from a tensor to a numPy array when on a gpu. But you can move a tensor back to the cpu**
### Device Agnostic
It is reccomended to have device agnostic code.
For device agnostic code checkout this <a href="https://pytorch.org/docs/stable/notes/cuda.html">link</a>
E.g. run on GPU if available else default to CPU

### Check for GPU Access

In [42]:
import torch
torch.cuda.is_available()

True

In [45]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [46]:
# you can also count the number of gpus
torch.cuda.device_count()

1

## Putting tensors on the GPU

In [47]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
# Tensor not on GPU
tensor.device

device(type='cpu')

In [48]:
# Move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [49]:
tensor_on_gpu[0] = 2
tensor, tensor_on_gpu

(tensor([1, 2, 3]), tensor([2, 2, 3], device='cuda:0'))

In [50]:
# Move back to cpu
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy() # This would fail on a gpu

array([2, 2, 3])

# Excercises
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises


In [51]:
import torch
# 2. Create a random tensor with shape (7, 7).
ran = torch.rand(7, 7)
ran.shape

torch.Size([7, 7])

In [54]:
# 3 Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
ran2 = torch.rand(1, 7)
torch.mm(ran, ran2.T)

tensor([[1.1679],
        [1.3314],
        [1.6210],
        [2.0120],
        [0.9991],
        [1.2929],
        [1.2112]])

In [55]:
# 4 Set the random seed to 0 and do exercises 2 & 3 over again.
SEED = 0
torch.manual_seed(SEED)
ran = torch.rand(7, 7)
torch.manual_seed(SEED)
ran2 = torch.rand(1, 7)
torch.mm(ran, ran2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [61]:
# 5 Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
GPU_SEED = 1234
torch.cuda.manual_seed(GPU_SEED)
# 6 Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(GPU_SEED)
ran = torch.rand(2, 3).to(device)
torch.manual_seed(GPU_SEED)
ran2 = torch.rand(2, 3).to(device)
ran.device, ran2.device, ran == ran2

(device(type='cuda', index=0),
 device(type='cuda', index=0),
 tensor([[True, True, True],
         [True, True, True]], device='cuda:0'))

In [64]:
# 7 Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
result = ran.mm(ran2.T)
result

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [65]:
# 8 Find the maximum and minimum values of the output of 7.
result.max(), result.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [66]:
# 9 Find the maximum and minimum index values of the output of 7.
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [70]:
# 10 Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
x = torch.rand(1, 1, 1, 10)
y = x.squeeze()
x, x.shape, y, y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))